DOMAIN = "bhk_integration"

CONF_GATEWAY_MAC = "mac"
CONF_GATEWAY_IP = "ip"
CONF_GATEWAY_TYPE = "type"
CONF_RETRY_INTERVAL = "retry_interval"

DISCOVERY_MESSAGE = "DISCOVER_GATEWAY"
DISCOVERY_BROADCAST_PORT = 50000
GATEWAY_RESPONSE_PORT = 50002
DEFAULT_RETRY_INTERVAL = 10
