DOMAIN = "bhk_integration"

CONF_GATEWAY_MAC = "mac"
CONF_GATEWAY_IP = "ip"
CONF_GATEWAY_TYPE = "type"
CONF_GATEWAY_HW_VERSION = "hardware_version"
CONF_GATEWAY_WS_PORT = "ws_port"
CONF_GATEWAY_WS_PATH = "ws_path"
CONF_RETRY_INTERVAL = "retry_interval"

DISCOVERY_MESSAGE = "DISCOVER_GATEWAY"
DISCOVERY_BROADCAST_PORT = 50000
GATEWAY_RESPONSE_PORT = 50002
DEFAULT_RETRY_INTERVAL = 10
DEFAULT_WEBSOCKET_PORT = 50001
DEFAULT_WEBSOCKET_PATH = "/ws"
